export const ADD_BURGER_INGREDIENT: 'ADD_BURGER_INGREDIENT' =
  'ADD_BURGER_INGREDIENT';
export const DELETE_BURGER_INGREDIENT: 'DELETE_BURGER_INGREDIENT' =
  'DELETE_BURGER_INGREDIENT';
export const REORDER_BURGER_INGREDIENTS: 'REORDER_BURGER_INGREDIENTS' =
  'REORDER_BURGER_INGREDIENTS';
export const RESET_BURGER_INGREDIENTS: 'RESET_BURGER_INGREDIENTS' =
  'RESET_BURGER_INGREDIENTS';
