export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const ORDER_RESET: 'ORDER_RESET' = 'ORDER_RESET';

export const ORDER_DATA_REQUEST: 'ORDER_DATA_REQUEST' = 'ORDER_DATA_REQUEST';
export const ORDER_DATA_SUCCESS: 'ORDER_DATA_SUCCESS' = 'ORDER_DATA_SUCCESS';
export const ORDER_DATA_ERROR: 'ORDER_DATA_ERROR' = 'ORDER_DATA_ERROR';
export const ORDER_DATA_RESET: 'ORDER_DATA_RESET' = 'ORDER_DATA_RESET';
