export const WS_PROFILE_START: 'WS_PROFILE_START' = 'WS_PROFILE_START';
export const WS_PROFILE_OPEN: 'WS_PROFILE_OPEN' = 'WS_PROFILE_OPEN';
export const WS_PROFILE_SUCCESS: 'WS_PROFILE_SUCCESS' = 'WS_PROFILE_SUCCESS';
export const WS_PROFILE_CLOSED: 'WS_PROFILE_CLOSED' = 'WS_PROFILE_CLOSED';
export const WS_PROFILE_DISCONNECT: 'WS_PROFILE_DISCONNECT' =
  'WS_PROFILE_DISCONNECT';
export const WS_PROFILE_ERROR: 'WS_PROFILE_ERROR' = 'WS_PROFILE_ERROR';
export const WS_PROFILE_MESSAGE: 'WS_PROFILE_MESSAGE' = 'WS_PROFILE_MESSAGE';
